# travis build for APhotoManager
language: android

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
# graphviz to render javadoc uml
# https://docs.travis-ci.com/user/multi-os/
      - graphviz

android:
  components:
    # https://github.com/travis-ci/travis-ci/issues/5036
    - tools

    # values in gradle.properties and .travis must be the same
    - build-tools-24.0.2
    - android-23

    - add-on
    - extra

before_install:
# http://stackoverflow.com/questions/33820638/travis-yml-gradlew-permission-denied
# must execute
# git update-index --chmod=+x gradlew
# instead of 
# - chmod +x gradlew
 
script:
  - jdk_switcher use oraclejdk8
  - ./gradlew assemble
